version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install
      - export BUCKET=codepipeline-us-east-1-516062891097
      - aws cloudformation package --template-file templateProd.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - templateProd.yml
    - outputtemplate.yml